#!/usr/bin/env bash

RED='\033[0;31m'
BOLD=$(tput bold)
NORMAL=$(tput sgr0)

error() {
  echo -e "${RED}Ошибка:${NORMAL} $1"
}

require_in_docer() {
  if [[ ! $IN_YOYO_DOCKER == 1 ]]; then
    echo 'Данная команда может быть вызвана только внутри запущенного Docker контейнера YoYo.'
    exit 1
  fi
}

wait_for_db() {
  require_in_docer

  export PGPASSWORD=$POSTGRES_PASSWORD
  RETRIES=10

  until psql -h $POSTGRES_HOST -U $POSTGRES_USER $POSTGRES_DB -c 'select 1' >/dev/null 2>&1 || [ $RETRIES -eq 0 ]; do
    echo "Ожидание запуска PostgreSQL, попытка подключения $((RETRIES--))..."
    sleep 2
  done
}

if [[ ! $IN_YOYO_DOCER == 1 ]]; then
  if ! command -v docker-compose >/dev/null 2>&1; then
    error 'У вас должен быть установлен Docker.'
    echo
    echo "Скачать Docker вы можете с этой страницы:"
    echo "https://www.docker.com/get-started"
    echo
    exit 1
  fi
fi


intro() {
  echo 'использование: ./dev [arg] ...'
  echo 'Аргументы сгруппированы по типу:'
  echo
  echo 'Для разработки:'
  echo
  echo "    ${BOLD}init${NOMAL}          ининциализая БД для разработчика."
  echo "    ${BOLD}afterinit${NOMAL}     повторно показать справку после завершения инициализации."
  echo "    ${BOLD}clear${NOMAL}         очистить медиа, а также удалить Docker контейнеры."
  echo "    ${BOLD}rebuild${NOMAL}       пересоздать Docker контейнер YoYo."
  echo "    ${BOLD}reset${NOMAL}         очистить после инициализации."
  echo
  echo "    Аргементы init и rebuild могут содержвать любое кол-во дополнительных опций."

}
