#!/usr/bin/env bash

RED='\033[0;31m'
BOLD=$(tput bold)
NORMAL=$(tput sgr0)

username=${DJANGO_SUPERUSER_NAME}
email=${DJANGO_SUPERUSER_EMAIL}
password=${DJANGO_SUPERUSER_PASSWORD}

error() {
  echo -e "${RED}Ошибка:${NORMAL} $1"
}

require_in_docer() {
  if [[ ! $IN_YOYO_DOCKER == 1 ]]; then
    echo 'Данная команда может быть вызвана только внутри запущенного Docker контейнера YoYo.'
    exit 1
  fi
}

wait_for_db() {
  require_in_docer

  export PGPASSWORD=$POSTGRES_PASSWORD
  RETRIES=10

  until psql -h $POSTGRES_HOST -U $POSTGRES_USER $POSTGRES_DB -c 'select 1' >/dev/null 2>&1 || [ $RETRIES -eq 0 ]; do
    echo "Ожидание запуска PostgreSQL, попытка подключения $((RETRIES--))..."
    sleep 2
  done
}

if [[ ! $IN_YOYO_DOCER == 1 ]]; then
  if ! command -v docker-compose >/dev/null 2>&1; then
    error 'У вас должен быть установлен Docker.'
    echo
    echo "Скачать Docker вы можете с этой страницы:"
    echo "https://www.docker.com/get-started"
    echo
    exit 1
  fi
fi


init_in_docker() {
  require_in_docer
  wait_for_db
  python manage.py migrate
  python manage.py collectstatic
  python manage.py cities_light --progress
  python manage.py createsuperuser --username $username --email $email --password $password
}

