version: '3.0'
services:
  postgres:
    image: mdillon/postgis
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '127.0.0.1:${YOYO_PSQL_PORT:-5432}:5432'
  yoyo:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - '${YOYO_DEVSERVER_PORT:-8000}:8000'
    depends_on:
      - postgres
    tty: true
    volumes:
    - .:/srv/yoyo:Z
