# Generated by Django 3.0.4 on 2020-03-19 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import yoyo.institutes.uploader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0008_city_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=yoyo.institutes.uploader.upload_logo, verbose_name='Logo')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'College/Academy'), (2, 'Vocational school'), (3, 'Courses')], default=1, verbose_name='Type of institution')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.City', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Institute',
                'verbose_name_plural': 'Institutes',
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=60, null=True, verbose_name='Document number')),
                ('doc_type', models.PositiveSmallIntegerField(choices=[(1, 'Diploma'), (2, 'Certificate')], default=1, verbose_name='Document type')),
                ('annotate', models.TextField(blank=True, null=True, verbose_name='Document annotate')),
                ('date_of_issue', models.DateField(verbose_name='Date of issue')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added at')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoyo_institutes.Institute', verbose_name='Institute')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-added_at'],
            },
        ),
    ]
