# Generated by Django 3.0.4 on 2020-03-21 13:55

from django.db import migrations, models
import yoyo.coaches.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('yoyo_coaches', '0005_coach_hero_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=yoyo.coaches.uploader.upload_main_photo, verbose_name='Main photo'),
        ),
    ]
