# Generated by Django 3.0.4 on 2020-03-16 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='E-mail')),
                ('email_hash', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Last name')),
                ('second_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Second name')),
                ('joined_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Joined on')),
                ('joined_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
