# Generated by Django 3.0.4 on 2020-03-18 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoyo_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
