name: Docker Image CI

on:
  push:
    branches: 
      - master
      - releases/*
  pull_request:
    branches: 
      - master 
      - releases/*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yoyo:$(date +%s)
